run:
  deadline: 5m
  issues-exit-code: 1
  tests: false

  skip-dirs:
    - .github
    - .vscode
    - testdata

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - durationcheck
    - errcheck
    - exportloopref
    - gocritic
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
    - wastedassign

issues:
  max-same-issues: 0
  exclude-rules:
    - linters:
        - gocritic
      text: "appendAssign"
    - path: _test\.go
      linters:
        - errcheck
        - revive
        - gosec
  exclude:
    - "unhandled-error: Unhandled error in call to function builder.Write.+"
    - "unhandled-error: Unhandled error in call to function fmt..+"
    - "Error return value of `cerr.Add` is not checked"

linters-settings:
  errcheck:
    ignoretests: true

  goimports:
    local-prefixes: github.com/prometheus/prometheus

  gofumpt:
    extra-rules: true

  revive:
    ignore-generated-header: true
    severity: "warning"
    confidence: 0.8
    enable-all-rules: true
    rules:
      - name: add-constant
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: empty-lines
        disabled: true
      - name: blank-imports
        disabled: true
      - name: file-header
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: function-length
        disabled: true
      - name: banned-characters
        disabled: true

      - name: argument-limit
        arguments: [5]
      - name: cyclomatic
        arguments: [15]
      - name: cognitive-complexity
        arguments: [15]
      - name: function-result-limit
        arguments: [3]
