name: Build and test
on: [push, pull_request]
jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.13, 1.14]
    steps:
      - 
        name: Checkout source code
        uses: actions/checkout@v2
      - 
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      -
        name: Install dependencies
        run: |
          go mod download
          go get -u github.com/rakyll/gotest
      -
        name: Build
        uses: magefile/mage-action@v1
        with:
          args: build
      - 
        name: Test with coverage
        uses: magefile/mage-action@v1
        with:
          args: cover
      - 
        name: Send coverage report to Codecov
        uses: codecov/codecov-action@v1
