name: Coverage

on:
  push:
    tags:
      - v*
    branches:
      - main
permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.20.x]

    name: go-coverage
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - name: Check test coverage
        run: make test-coverage
      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.out
